simple_rgbw2.groovy: build
	python3 ../../hubitat_hubspider.py push_code --filename simple_rgbw2.groovy --appid 1031

shelly_rgbw2.groovy: build
	python3 ../../hubitat_hubspider.py push_code --filename shelly_rgbw2.groovy --appid 593

build:
	echo "Building"
